/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'imageBlobKey' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'imageBlobKey' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlobKey' : IDL.Text,
});
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createStory' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'didUserLikePost' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], ['query']),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Story)))],
      ['query'],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getConversations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ChatMessage))],
      ['query'],
    ),
  'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPostLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'imageBlobKey' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'imageBlobKey' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlobKey' : IDL.Text,
  });
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createStory' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'didUserLikePost' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Bool],
        ['query'],
      ),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Story)))],
        ['query'],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ChatMessage))],
        ['query'],
      ),
    'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPostLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };